services:
  client:
    container_name: winner-crud-client
    build:
      context: .
      dockerfile: /client/Dockerfile
    working_dir: /app/client
    ports:
      - '5173:5173'
    environment:
      - APP_PORT=3000
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    command: 'npm run dev'
  db:
    image: postgres:10-alpine
    container_name: winner-crud-db
    networks:
      - winner-crud-net
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: winner_crud
    volumes:
      - db-data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    container_name: winner-crud-admin
    restart: always
    depends_on:
      - db
    networks:
      - winner-crud-net
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: example@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
  # Currently does not support hot reload
  # Related issue:
  # https://github.com/air-verse/air/issues/274
  # https://stackoverflow.com/questions/70321633/hot-reload-not-working-in-docker-with-golang-github-com-cosmtrek-air
  server:
    container_name: winner-crud-server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    working_dir: /app
    volumes:
      - D:\Personal\winners-crud\server:/app
    ports:
      - '4000:4000'
    command: air

networks:
  winner-crud-net:
    driver: bridge

volumes:
  db-data:
    driver: local
