services:
  client:
    container_name: winner-crud-client
    build:
      context: .
    working_dir: /app/client
    ports:
      - '5173:3000'
    environment:
      - APP_PORT=3000
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    command: 'npm run start'
