services:
  client:
    container_name: ${PROJECT_NAME}_client
    build:
      context: .
      dockerfile: /client/Dockerfile
    working_dir: /app/client
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    command: 'npm run dev'
  db:
    image: postgres:10-alpine
    container_name: ${PROJECT_NAME}_db
    networks:
      - winner-crud-net
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PROJECT_NAME}_pgadmin
    restart: always
    depends_on:
      - db
    networks:
      - winner-crud-net
    ports:
      - '${PGADMIN_PORT}:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  # Currently does not support hot reload
  # Related issue:
  # https://github.com/air-verse/air/issues/274
  # https://stackoverflow.com/questions/70321633/hot-reload-not-working-in-docker-with-golang-github-com-cosmtrek-air
  # server:
  #   container_name: winner-crud-server
  #   build:
  #     context: .
  #     dockerfile: ./server/Dockerfile
  #   working_dir: /app
  #   volumes:
  #     - D:\Personal\winners-crud\server:/app
  #   ports:
  #     - '4000:4000'
  #   command: air

networks:
  winner-crud-net:
    driver: bridge

volumes:
  db-data:
    driver: local
