services:
  client:
    container_name: winner-crud-client
    build:
      context: .
    working_dir: /app/client
    ports:
      - '5173:5173'
    environment:
      - APP_PORT=3000
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    command: 'npm run dev'
  db:
    image: postgres:10-alpine
    container_name: winner-crud-db
    networks:
      - winner-crud-net
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: winner_crud
    volumes:
      - db-data:/var/lib/postgresql/data

  admin:
    image: adminer
    container_name: winner-crud-admin
    restart: always
    depends_on:
      - db
    networks:
      - winner-crud-net
    ports:
      - '8080:8080'

networks:
  winner-crud-net:
    driver: bridge

volumes:
  db-data:
    driver: local
